[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (добавить OPENAI_API_KEY через Netlify Dashboard)
# https://app.netlify.com/sites/YOUR-SITE/settings/deploys#environment

